### ISSUE TITLE
Crash on Forge 1.18.2

### ISSUE THREAD

**Issue by Zano1999** [Alex-the-666/DomesticationInnovation#27]
[21apr2022 21:27:44.029] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Zano1999, --version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Nicolas\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Nicolas\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 5b888b4e83ff4caeb4964eec8270b00e, --accessToken, ????????, --clientId, OGU0ODRkODQtMDQ4MC00YjIzLTljNGMtMzA1MDNhNjRkNzEx, --xuid, 2535431273484458, --userType, msa, --versionType, release, --width, 1920, --height, 1080, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[21apr2022 21:27:44.033] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.2 by Eclipse Adoptium
[21apr2022 21:27:44.230] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[21apr2022 21:27:44.231] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/C:/Users/Nicolas/AppData/Roaming/.minecraft/mods/OptiFine_1.18.2_HD_U_H6.jar%2352!/
[21apr2022 21:27:44.241] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\Nicolas\AppData\Roaming\.minecraft\mods\OptiFine_1.18.2_HD_U_H6.jar
[21apr2022 21:27:44.243] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[21apr2022 21:27:44.315] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Nicolas/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[21apr2022 21:27:44.323] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[21apr2022 21:27:45.414] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: citadel
[21apr2022 21:27:45.830] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[21apr2022 21:27:45.837] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 347
[21apr2022 21:27:46.273] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[21apr2022 21:27:47.429] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[21apr2022 21:27:47.700] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Nicolas\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Nicolas\AppData\Roaming\.minecraft\assets, --uuid, 5b888b4e83ff4caeb4964eec8270b00e, --username, Zano1999, --assetIndex, 1.18, --accessToken, ????????, --clientId, OGU0ODRkODQtMDQ4MC00YjIzLTljNGMtMzA1MDNhNjRkNzEx, --xuid, 2535431273484458, --userType, msa, --versionType, release, --width, 1920, --height, 1080]
[21apr2022 21:27:55.822] [pool-3-thread-1/WARN] [mixin/]: @ModifyConstant conflict. Skipping yungsapi.mixins.json:IncreaseStructureWeightLimitMixin->@ModifyConstant::yungsapi_increaseWeightLimit(I)I with priority 1000, already redirected by repurposed_structures.mixins.json:structures.StructurePoolMixin->@ModifyConstant::repurposedstructures_increaseWeightLimitDev(I)I with priority 1000
[21apr2022 21:27:56.185] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `collar_tag`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.185] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `magnet_loop`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.186] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `chain_lightning`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.186] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `giant_bubble_inflate`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.186] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `giant_bubble_pop`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.186] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `pet_bed_use`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.186] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `drum`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.186] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `psychic_wall`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.187] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `psychic_wall_deflect`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.187] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `animal_tamer`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.221] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `health_boost`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.223] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `fireproof`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.223] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `immunity_frame`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.223] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `deflection`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.223] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `poison_resistance`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.223] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `chain_lightning`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.224] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `speedster`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.224] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `frost_fang`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.224] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `magnetic`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.225] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `linked_inventory`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.225] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `total_recall`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.225] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `health_siphon`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.225] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `bubbling`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.225] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `herding`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.225] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `amphibious`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.226] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `vampire`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.227] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `void_cloud`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.227] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `charisma`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.228] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `shadow_hands`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.228] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `disc_jockey`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.228] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `defusal`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.228] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `warping_bite`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.228] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `ore_scenting`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.229] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `gluttonous`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.229] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `psychic_wall`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.229] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `intimidation`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.229] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `undead_curse`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.229] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `infamy_curse`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[21apr2022 21:27:56.229] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `blight_curse`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.

**Comment by Alex-the-666** [comment]
fixed in 1.3.1

**Comment by Zano1999** [comment]
Still crash:

[22apr2022 22:01:36.019] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Zano1999, --version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Nicolas\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Nicolas\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 5b888b4e83ff4caeb4964eec8270b00e, --accessToken, ????????, --clientId, OGU0ODRkODQtMDQ4MC00YjIzLTljNGMtMzA1MDNhNjRkNzEx, --xuid, 2535431273484458, --userType, msa, --versionType, release, --width, 1920, --height, 1080, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[22apr2022 22:01:36.023] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.2 by Eclipse Adoptium
[22apr2022 22:01:36.223] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[22apr2022 22:01:36.225] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/C:/Users/Nicolas/AppData/Roaming/.minecraft/mods/OptiFine_1.18.2_HD_U_H6.jar%2352!/
[22apr2022 22:01:36.235] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\Nicolas\AppData\Roaming\.minecraft\mods\OptiFine_1.18.2_HD_U_H6.jar
[22apr2022 22:01:36.238] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[22apr2022 22:01:36.299] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Nicolas/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[22apr2022 22:01:36.308] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[22apr2022 22:01:37.400] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: citadel
[22apr2022 22:01:37.816] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[22apr2022 22:01:37.823] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 347
[22apr2022 22:01:38.324] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[22apr2022 22:01:39.646] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[22apr2022 22:01:39.844] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Nicolas\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Nicolas\AppData\Roaming\.minecraft\assets, --uuid, 5b888b4e83ff4caeb4964eec8270b00e, --username, Zano1999, --assetIndex, 1.18, --accessToken, ????????, --clientId, OGU0ODRkODQtMDQ4MC00YjIzLTljNGMtMzA1MDNhNjRkNzEx, --xuid, 2535431273484458, --userType, msa, --versionType, release, --width, 1920, --height, 1080]
[22apr2022 22:01:46.725] [pool-3-thread-1/WARN] [mixin/]: @ModifyConstant conflict. Skipping yungsapi.mixins.json:IncreaseStructureWeightLimitMixin->@ModifyConstant::yungsapi_increaseWeightLimit(I)I with priority 1000, already redirected by repurposed_structures.mixins.json:structures.StructurePoolMixin->@ModifyConstant::repurposedstructures_increaseWeightLimitDev(I)I with priority 1000
[22apr2022 22:01:47.054] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `collar_tag`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.054] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `magnet_loop`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.054] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `chain_lightning`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.054] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `giant_bubble_inflate`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.055] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `giant_bubble_pop`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.055] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `pet_bed_use`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.055] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `drum`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.055] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `psychic_wall`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.055] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `psychic_wall_deflect`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.055] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `animal_tamer`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.116] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `health_boost`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.116] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `fireproof`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.116] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `immunity_frame`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.116] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `deflection`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.117] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `poison_resistance`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.117] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `chain_lightning`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.117] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `speedster`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.117] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `frost_fang`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.117] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `magnetic`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.117] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `linked_inventory`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.117] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `total_recall`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.118] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `health_siphon`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.118] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `bubbling`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.118] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `herding`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.118] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `amphibious`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.118] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `vampire`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.118] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `void_cloud`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `charisma`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `shadow_hands`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `disc_jockey`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `defusal`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `warping_bite`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `ore_scenting`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `gluttonous`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `psychic_wall`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.119] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `intimidation`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.120] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `undead_curse`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.120] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `infamy_curse`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[22apr2022 22:01:47.120] [pool-3-thread-1/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `domesticationinnovation` for name `blight_curse`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
